version: '2'
services:
  boringgame-mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: top_secret
      MYSQL_DATABASE: boringGameDB
      MYSQL_USER: boring_game
      MYSQL_PASSWORD: secret

    ports:
      - 3306:3306
